import type { NavigationContext, RouteConfig } from '../navigation-config';

// Main app routes (world-dependent)
export const MAIN_ROUTES: RouteConfig[] = [
  {
    path: '/main/main-landing',
    title: 'D&D Toolkit',
    showTopBar: true,
    showHamburger: true,
    requiredParams: ['worldId', 'userRole'],
    preserveParamsOnBack: ['worldId', 'userRole'],
    animation: 'slide',
    analyticsName: 'main_landing',
    redirectIf: (context: NavigationContext) => {
      if (!context.worldId) {
        return '/select/world-selection'
      }
      return undefined
    },
    onError: (error: Error, context: NavigationContext) => {
      console.error('[Route Error] main-landing:', error.message)
      context.router.replace('/select/world-selection')
    },
  },
// Characters & NPCs
  {
    path: '/main/characters-npcs',
    title: 'Characters & NPCs',
    showTopBar: true,
    back: '/main/main-landing',
    requiredParams: ['worldId', 'userRole'],
    preserveParamsOnBack: ['worldId', 'userRole'],
    analyticsName: 'main_characters',
  },
  {
    path: '/main/characters-npcs/character-sheets',
    title: 'Character Sheets',
    showTopBar: true,
    back: '/main/main-landing',
    requiredParams: ['worldId', 'userRole'],
    preserveParamsOnBack: ['worldId', 'userRole'],
    analyticsName: 'main_character_sheets',
  },
    {
    path: '/main/characters-npcs/faction-tracker',
    title: 'Character Sheets',
    showTopBar: true,
    back: '/main/main-landing',
    requiredParams: ['worldId', 'userRole'],
    preserveParamsOnBack: ['worldId', 'userRole'],
    analyticsName: 'main_character_sheets',
  },
    {
    path: '/main/characters-npcs/npc-forge',
    title: 'Character Sheets',
    showTopBar: true,
    back: '/main/main-landing',
    requiredParams: ['worldId', 'userRole'],
    preserveParamsOnBack: ['worldId', 'userRole'],
    analyticsName: 'main_character_sheets',
  },
    {
    path: '/main/characters-npcs/party-overview',
    title: 'Character Sheets',
    showTopBar: true,
    back: '/main/main-landing',
    requiredParams: ['worldId', 'userRole'],
    preserveParamsOnBack: ['worldId', 'userRole'],
    analyticsName: 'main_character_sheets',
  },
  // Items & Treasure
  {
    path: '/main/items-treasure',
    title: 'Items & Treasure',
    showTopBar: true,
    back: '/main/main-landing',
    requiredParams: ['worldId', 'userRole'],
    preserveParamsOnBack: ['worldId', 'userRole'],
    analyticsName: 'main_items',
  },
  {
    path: '/main/items-treasure/inventory',
    title: 'Inventory',
    showTopBar: true,
    back: '/main/main-landing',
    requiredParams: ['worldId', 'userRole'],
    preserveParamsOnBack: ['worldId', 'userRole'],
    analyticsName: 'main_items_inventory',
  },
  {
    path: '/main/items-treasure/party-loot',
    title: 'Party Loot',
    showTopBar: true,
    back: '/main/main-landing',
    requiredParams: ['worldId', 'userRole'],
    preserveParamsOnBack: ['worldId', 'userRole'],
    analyticsName: 'main_items_party_loot',
  },
  {
    path: '/main/items-treasure/shop-generator',
    title: 'Shop Generator',
    showTopBar: true,
    back: '/main/main-landing',
    requiredParams: ['worldId', 'userRole'],
    preserveParamsOnBack: ['worldId', 'userRole'],
    analyticsName: 'main_items_shop_generator',
  },
  {
    path: '/main/items-treasure/treasure-generator',
    title: 'Treasure Generator',
    showTopBar: true,
    back: '/main/main-landing',
    requiredParams: ['worldId', 'userRole'],
    preserveParamsOnBack: ['worldId', 'userRole'],
    analyticsName: 'main_items_treasure_generator',
  },

  // World & Exploration
  {
    path: '/main/world-exploration',
    title: 'World & Exploration',
    showTopBar: true,
    back: '/main/main-landing',
    requiredParams: ['worldId', 'userRole'],
    preserveParamsOnBack: ['worldId', 'userRole'],
    analyticsName: 'main_world',
  },
  {
    path: '/main/world-exploration/world-map',
    title: 'World Map',
    showTopBar: true,
    back: '/main/main-landing',
    requiredParams: ['worldId', 'userRole'],
    preserveParamsOnBack: ['worldId', 'userRole'],
    analyticsName: 'main_world_map',
  },
  {
    path: '/main/world-exploration/weather-generator',
    title: 'Weather Generator',
    showTopBar: true,
    back: '/main/main-landing',
    requiredParams: ['worldId', 'userRole'],
    preserveParamsOnBack: ['worldId', 'userRole'],
    analyticsName: 'main_world_weather',
  },
  {
    path: '/main/world-exploration/dungeon-town-creator',
    title: 'Dungeon & Town Creator',
    showTopBar: true,
    back: '/main/main-landing',
    requiredParams: ['worldId', 'userRole'],
    preserveParamsOnBack: ['worldId', 'userRole'],
    analyticsName: 'main_world_dungeon_town',
  },
  {
    path: '/main/world-exploration/battle-map-maker',
    title: 'Battle Map Maker',
    showTopBar: true,
    back: '/main/main-landing',
    requiredParams: ['worldId', 'userRole'],
    preserveParamsOnBack: ['worldId', 'userRole'],
    analyticsName: 'main_world_battle_map',
  },

  // Combat & Events
  {
    path: '/main/combat-events',
    title: 'Combat & Events',
    showTopBar: true,
    back: '/main/main-landing',
    requiredParams: ['worldId', 'userRole'],
    preserveParamsOnBack: ['worldId', 'userRole'],
    analyticsName: 'main_combat',
  },
  {
    path: '/main/combat-events/calendar',
    title: 'Calendar',
    showTopBar: true,
    back: '/main/main-landing',
    requiredParams: ['worldId', 'userRole'],
    preserveParamsOnBack: ['worldId', 'userRole'],
    analyticsName: 'main_combat_calendar',
  },
  {
    path: '/main/combat-events/encounter-builder',
    title: 'Encounter Builder',
    showTopBar: true,
    back: '/main/main-landing',
    requiredParams: ['worldId', 'userRole'],
    preserveParamsOnBack: ['worldId', 'userRole'],
    analyticsName: 'main_combat_encounter',
  },
  {
    path: '/main/combat-events/event-builder',
    title: 'Event Builder',
    showTopBar: true,
    back: '/main/main-landing',
    requiredParams: ['worldId', 'userRole'],
    preserveParamsOnBack: ['worldId', 'userRole'],
    analyticsName: 'main_combat_event',
  },
  {
    path: '/main/combat-events/initiative-tracker',
    title: 'Initiative Tracker',
    showTopBar: true,
    back: '/main/main-landing',
    requiredParams: ['worldId', 'userRole'],
    preserveParamsOnBack: ['worldId', 'userRole'],
    analyticsName: 'main_combat_initiative',
  },

  // Story & Notes
  {
    path: '/main/story-notes',
    title: 'Story & Notes',
    showTopBar: true,
    back: '/main/main-landing',
    requiredParams: ['worldId', 'userRole'],
    preserveParamsOnBack: ['worldId', 'userRole'],
    analyticsName: 'main_story',
  },
  {
    path: '/main/story-notes/notes',
    title: 'Notes',
    showTopBar: true,
    back: '/main/main-landing',
    requiredParams: ['worldId', 'userRole'],
    preserveParamsOnBack: ['worldId', 'userRole'],
    analyticsName: 'main_story_notes',
  },
  {
    path: '/main/story-notes/journal',
    title: 'Journal',
    showTopBar: true,
    back: '/main/main-landing',
    requiredParams: ['worldId', 'userRole'],
    preserveParamsOnBack: ['worldId', 'userRole'],
    analyticsName: 'main_story_journal',
  },
  {
    path: '/main/story-notes/handouts',
    title: 'Handouts',
    showTopBar: true,
    back: '/main/main-landing',
    requiredParams: ['worldId', 'userRole'],
    preserveParamsOnBack: ['worldId', 'userRole'],
    analyticsName: 'main_story_handouts',
  },
  {
    path: '/main/story-notes/quest-log',
    title: 'Quest Log',
    showTopBar: true,
    back: '/main/main-landing',
    requiredParams: ['worldId', 'userRole'],
    preserveParamsOnBack: ['worldId', 'userRole'],
    analyticsName: 'main_story_quest_log',
  },
]
